# for dev use
# create `docker-compose.yaml` file
# copy the configs and add your secret to environment
services:
  api:
    container_name: api
    image: tentrek-api:dev
    build:
      context: .
      dockerfile: dockerfile
    environment:
      API_SERVER_PORT: ':8080'

      DB_HOST: 'host.docker.internal'
      DB_USER: 'tentrek'
      DB_PASSWORD: 'tentrek'
      DB_DBNAME: 'tentrek_db'

      APP_BASE_URL: 'http://localhost:3000'

      JWT_SECRET: 'jwtjwtjwt'

      # add your OTP email sender
      SMTP_SENDER: ''
      SMTP_SENDER_PASSWORD: ''
      SMTP_HOST: ''
      SMTP_PORT: ''

      # add your oauth client
      SESSION_KEY: ''
      GOOGLE_OAUTH_CLIENT_ID: ''
      GOOGLE_OAUTH_CLIENT_SECRET: ''
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: 'tentrek'
      POSTGRES_PASSWORD: 'tentrek'
      POSTGRES_DB: 'tentrek_db'
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data: {}
