services:
  api:
    container_name: api
    image: tentrek-api:1.0.0
    build:
      context: .
      dockerfile: dockerfile
    environment:
      API_SERVER_PORT: ':8080'
      DB_HOST: 'host.docker.internal'
      DB_USER: 'tentrek'
      DB_PASSWORD: 'tentrek'
      DB_DBNAME: 'tentrek_db'
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: 'tentrek'
      POSTGRES_PASSWORD: 'tentrek'
      POSTGRES_DB: 'tentrek_db'
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data: {}
