FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . ./internal

RUN go build -v -o ./bin/tentrek ./internal/main.go

EXPOSE 8080

CMD ["/app/bin/tentrek"]
